// Offline demo genome: human GRCh38 chr13:32,315,300-32,316,500 — the 5' end of
// BRCA2. Doubles as a worked example of a `static` provider genome.

const SEQ = `
GAAGAGAACACACACTCCAGCTCCCGCTTTATTCGGTCAGATACTGACGGTTGGGATGCCTGACAAGGAATT
TCCTTTCGCCACACTGAGAAATACCCGCAGCGGCCCACCCAGGCCTGACTTCCGGGTGGTGCGTGTGCTGCG
TGTCGCGTCACGGCGTCACGTGGCCAGCGCGGGCTTGTGGCGCGAGCTTCTGAAACTAGGCGGCAGAGGCGG
AGCCGCTGTGGCACTGCTGCGCCTCTGCTGCGCCTCGGGTGTCTTTTGCGGCGGTGGGTCGCCGCCGGGAGA
AGCGTGAGGGGACAGATTTGTGACCGGCGCGGTTTTTGTCAGCTTACTCCGGCCAAAAAAGAACTGCACCTC
TGGAGCGGGTTAGTGGTGGTGGTAGTGGGTTGGGACGAGCGCGTCTTCCGCAGTCCCAGTCCAGCGTGGCGG
GGGAGCGCCTCACGCCCCGGGTCGCTGCCGCGGCTTCTTGCCCTTTTGTCTCTGCCAACCCCCACCCATGCC
TGAGAGAAAGGTCCTTGCCCGAAGGCAGATTTTCGCCAAGCAAATTCGAGCCCCGCCCCTTCCCTGGGTCTC
CATTTCCCGCCTCCGGCCCGGCCTTTGGGCTCCGCCTTCAGCTCAAGACTTAACTTCCCTCCCAGCTGTCCC
AGATGACGCCATCTGAAATTTCTTGGAAACACGATCACTTTAACGGAATATTGCTGTTTTGGGGAAGTGTTT
TACAGCTGCTGGGCACGCTGTATTTGCCTTACTTAAGCCCCTGGTAATTGCTGTATTCCGAAGACATGCTGA
TGGGAATTACCAGGCGGCGTTGGTCTCTAACTGGAGCCCTCTGTCCCCACTAGCCACGCGTCACTGGTTAGC
GTGATTGAAACTAAATCGTATGAAAATCCTCTTCTCTAGTCGCACTAGCCACGTTTCGAGTGCTTAATGTGG
CTAGTGGCACCGGTTTGGACAGCACAGCTGTAAAATGTTCCCATCCTCACAGTAAGCTGTTACCGTTCCAGG
AGATGGGACTGAATTAGAATTCAAACAAATTTTCCAGCGCTTCTGAGTTTTACCTCAGTCACATAATAAGGA
ATGCATCCCTGTGTAAGTGCATTTTGGTCTTCTGTTTTGCAGACTTATTTACCAAGCATTGGAGGAATATCG
TAGGTAAAAATGCCTATTGGATCCAAAGAGAGGCCAACATTTTTTGAAA
`.replace(/\s+/g, '')

export const DEMO_GENOME = {
  id: 'demo-brca2',
  organism: 'Demo',
  assembly: 'BRCA2 5\' end (offline)',
  provider: 'static',
  note: 'Bundled 1.2 kb of BRCA2. Works with no network.',
  maxRegionBp: 1201,
  data: {
    chrom: '13',
    start: 32315300,
    end: 32316500,
    seq: SEQ,
    genes: [
      { id: 'ENSG00000139618', name: 'BRCA2', chrom: '13', start: 32315086, end: 32400268, strand: 1 },
    ],
    features: [
      { id: 'ENSG00000139618', type: 'gene', name: 'BRCA2', start: 32315086, end: 32400268, strand: 1 },
      { id: 'ENSE00004020679', type: 'exon', name: 'exon 1', start: 32315496, end: 32315667, strand: 1 },
    ],
  },
}
